"""Constants and keyword maps for ticket analytics."""

from __future__ import annotations

from typing import Dict, List

COLUMN_ALIASES: Dict[str, List[str]] = {
    "ticket_id": [
        "ticket_id",
        "incident_id",
        "number",
        "id",
        "ticket_number",
        "incident_number",
        "task_id",
        "case_id",
        "incident",
    ],
    "ticket_type": [
        "ticket_type",
        "type",
        "incident_type",
        "request_type",
        "record_type",
    ],
    "description": [
        "description",
        "short_description",
        "summary",
        "details",
        "incident_description",
        "issue_description",
        "problem_description",
        "title",
    ],
    "team": [
        "team",
        "assignment_group",
        "resolver_group",
        "support_group",
        "group",
        "assignment_group_name",
        "support_team",
        "resolver_team",
        "assigned_group",
    ],
    "status": [
        "status",
        "state",
        "ticket_status",
        "incident_state",
        "current_status",
        "incident_status",
    ],
    "priority": [
        "priority",
        "severity",
        "impact_priority",
        "urgency",
        "priority_level",
        "priority_code",
    ],
    "service": [
        "service",
        "business_service",
        "application",
        "app",
        "system",
        "service_name",
        "service_offering",
        "business_service_name",
        "application_name",
        "application_service",
        "application_service_name",
        "service_application",
        "app_name",
        "impacted_application",
        "affected_application",
    ],
    "category": [
        "category",
        "incident_category",
        "issue_category",
        "category_name",
    ],
    "subcategory": [
        "sub_category",
        "subcategory",
        "sub_issue_type",
        "issue_subcategory",
        "issue_sub_type",
    ],
    "created_at": [
        "created_at",
        "opened_at",
        "opened",
        "opened_date",
        "opened_datetime",
        "created",
        "open_time",
        "start_time",
        "opened_on",
        "created_on",
        "open_date",
        "submission_date",
        "open_datetime",
    ],
    "resolved_at": [
        "resolved_at",
        "closed_at",
        "resolved",
        "resolved_datetime",
        "closed",
        "end_time",
        "resolution_time_stamp",
        "resolved_on",
        "resolved_date",
        "closed_on",
        "close_date",
        "resolution_date",
        "completion_date",
    ],
    "updated_at": ["updated_at", "last_updated", "modified_at", "updated_on", "last_modified"],
    "resolution_time": [
        "resolution_time",
        "time_to_resolve",
        "ttr",
        "mttr",
        "resolution_duration",
        "resolve_time",
        "time_to_resolution",
        "resolution_age",
        "time_spent",
    ],
    "response_sla": ["response_sla", "response_target", "response_time_target"],
    "resolution_sla": ["resolution_sla", "resolution_target", "resolution_time_target"],
    "reopen_count": ["reopen_count", "reopened", "reopens", "re_open_count", "reopen_counter"],
    "assignee": ["assignee", "assigned_to", "owner", "agent", "resolver", "technician", "resolved_by"],
    "closure_notes": ["closure_notes", "close_notes", "resolution_notes", "work_notes", "worknotes"],
    "cluster": ["cluster", "tower", "workstream", "domain_cluster"],
    "domain": ["domain", "application_domain", "business_domain"],
    "sub_domain": ["sub_domain", "subdomain", "business_function", "application_subdomain"],
    "contact_channel": ["contact_channel", "channel", "intake_channel", "source_channel", "contact_type"],
    "customer": ["customer", "client", "account_name"],
    "environment": ["environment", "env", "landscape"],
    "company": ["company", "organization", "org"],
    "affected_system": ["affected_system", "affected_asset", "ci_name", "configuration_item"],
    "department": ["department", "dept", "business_unit"],
    "requester_job_title": ["requester_job_title", "job_title", "requestor_title", "requested_for_title"],
    "location": ["location", "site", "office_location", "region"],
}

PRD_MANDATORY_FIELDS = {
    "ticket_id": "Incident Number",
    "team": "Assignment Group",
    "service": "Application",
}

PRD_OPTIONAL_FIELDS = {
    "created_at": "Open Date",
    "resolved_at": "Resolved Date",
    "status": "State",
    "priority": "Priority",
    "ticket_type": "Ticket Type",
    "category": "Issue Category",
    "subcategory": "Subcategory",
    "domain": "Domain",
    "sub_domain": "Sub Domain",
    "assignee": "Resolved By",
    "resolution_time": "Resolution Time",
    "response_sla": "Response SLA",
    "resolution_sla": "Resolution SLA",
    "closure_notes": "Closure Notes",
    "contact_channel": "Contact Channel",
    "cluster": "Tower/Cluster/Workstream",
    "customer": "Customer",
    "environment": "Environment",
    "company": "Company",
    "affected_system": "Affected System",
    "department": "Department",
    "requester_job_title": "Requester Job Title",
    "location": "Location",
}

GLOBAL_FILTER_CANDIDATES = [
    "priority",
    "team",
    "service",
    "category_derived",
    "business_function_derived",
    "domain",
    "sub_domain",
    "cluster",
    "ticket_type",
    "status",
]

RESOLVED_STATUSES = {
    "resolved",
    "closed",
    "completed",
    "done",
    "fulfilled",
}

OPEN_STATUSES = {
    "new",
    "open",
    "in_progress",
    "pending",
    "assigned",
    "on_hold",
    "reopened",
}

PRIORITY_MAP = {
    "1": "P1",
    "p1": "P1",
    "critical": "P1",
    "sev1": "P1",
    "severity1": "P1",
    "2": "P2",
    "p2": "P2",
    "high": "P2",
    "sev2": "P2",
    "severity2": "P2",
    "3": "P3",
    "p3": "P3",
    "medium": "P3",
    "moderate": "P3",
    "sev3": "P3",
    "severity3": "P3",
    "4": "P4",
    "p4": "P4",
    "low": "P4",
    "minor": "P4",
    "sev4": "P4",
    "severity4": "P4",
}

SLA_THRESHOLD_HOURS = {
    "P1": 4,
    "P2": 8,
    "P3": 24,
    "P4": 72,
    "Unknown": 24,
}

CATEGORY_KEYWORDS = {
    "Hardware": [
        "laptop",
        "desktop",
        "server",
        "printer",
        "keyboard",
        "mouse",
        "monitor",
        "usb",
        "device",
        "hardware",
    ],
    "Software": [
        "software",
        "application",
        "app",
        "workspace",
        "crash",
        "bug",
        "upgrade",
        "install",
        "office",
        "browser",
        "middleware",
    ],
    "Network": [
        "network",
        "vpn",
        "latency",
        "bandwidth",
        "dns",
        "firewall",
        "dhcp",
        "connectivity",
    ],
    "Accounts & Access": [
        "access",
        "password",
        "login",
        "unlock",
        "mfa",
        "permission",
        "authentication",
        "authorization",
        "remote access",
    ],
    "Communication": [
        "email",
        "outlook",
        "mailbox",
        "smtp",
        "exchange",
        "voip",
        "phone",
        "conference",
    ],
    "Database": ["database", "sql", "oracle", "postgres", "query", "db", "replication"],
    "Security": [
        "security",
        "malware",
        "phishing",
        "vulnerability",
        "breach",
        "threat",
        "virus",
    ],
    "Facilities": ["power", "hvac", "access control", "physical security", "facility"],
    "Other": ["other", "general", "unknown"],
}

BUSINESS_FUNCTION_KEYWORDS = {
    "IT Operations": ["infra", "infrastructure", "ops", "network", "server", "platform"],
    "Engineering": ["engineering", "dev", "code", "release", "deployment", "ci/cd"],
    "Finance": ["invoice", "payment", "expense", "finance", "erp", "sap"],
    "HR": ["hr", "payroll", "benefits", "employee", "onboarding"],
    "Sales": ["crm", "salesforce", "lead", "opportunity", "quote"],
    "Customer Support": ["customer", "support", "helpdesk", "case"],
    "Security": ["security", "soar", "siem", "soc", "threat"],
    "Operations": ["supply", "logistics", "warehouse", "operations", "fulfillment"],
    "Public Sector": ["federal", "state", "agency", "government"],
    "Healthcare": ["clinical", "pharma", "medical", "patient"],
    "Retail": ["retail", "store", "pos", "commerce"],
    "Energy": ["energy", "utility", "oil", "gas", "mining"],
}

CHART_KEYWORDS = {
    "bar": "bar",
    "column": "bar",
    "line": "line",
    "trend": "line",
    "time series": "line",
    "pie": "pie",
    "donut": "pie",
    "histogram": "histogram",
    "distribution": "histogram",
    "scatter": "scatter",
    "heatmap": "heatmap",
}

PRD_GRAPH_IDS = {
    "graph_1": "Ticket Trend Analysis",
    "graph_2": "SLA Breach Trend",
    "graph_3": "Top Issue Categories",
    "graph_4": "Top MTTR Groups",
    "graph_5": "Top Recurring Issues",
    "graph_6": "Team Performance",
    "graph_7": "Top Aged Open Tickets",
    "graph_8": "Time Trend Analysis",
}
